### ISSUE TITLE
add flogo extension for hyperledger-fabric

### ISSUE THREAD

**Issue by yxuco** [TIBCOSoftware/dovetail-contrib#36]
extensions for fabric chaincode and fabric client

**Comment by yxuco** [comment]
Completed implementation of FE extensions for fabric. More enhancements include the following:
* Support fabric-ca activities for client certificates
* Support ABAC with client certificates
* Generate contract schema from chaincode model, (https://fabric-shim.github.io/release-1.4/contract-schema.json) -- depending on FE 2.6 feature
* Improve UI for shared data and contract schema definitions
* Support dev/test in TCI environment
* Support deployment to AWS and Azure
* Support jsonata data mapping (?)
* Support fabric 2.0 chaincode lifecycle (?)

**Comment by torresashjian** [comment]
Finished! Closing
